table DimProduct
	lineageTag: fb96c848-0915-4ac6-a341-496c20db8b3e

	column ProductID
		dataType: string
		lineageTag: 612abd98-e48d-40a2-ace0-1160f3b78974
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 0d85082d-f641-4765-9758-123a6a5b2780
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d1073a55-a3dc-4d35-b981-8fc6f916508e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: c9e0c3a5-fec4-4ee4-b7d3-2ae0df260a14
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\marku\Projects\github\sales-reporting-automation\data\raw\Products.xlsx"), null, true),
				    Sheet = Source{[Item="Sheet1", Kind="Sheet"]}[Data],
				    PromotedHeaders = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(PromotedHeaders, {{"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"UnitCost", type number}}),
				    Cleaned = Table.TransformColumns(Typed, {
				        {"ProductID", each Text.Trim(_), type text},
				        {"ProductName", each Text.Trim(_), type text},
				        {"Category", each Text.Trim(_), type text}
				    })
				in
				    Cleaned

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

